In [2]:
import pandas as pd
import numpy as np

## Bước 1: Tải dữ liệu

Alcohol  Malic_Acid   Ash  ...  OD280  Proline  Customer_Segment
0      14.23        1.71  2.43  ...   3.92     1065                 1
1      13.20        1.78  2.14  ...   3.40     1050                 1
2      13.16        2.36  2.67  ...   3.17     1185                 1
3      14.37        1.95  2.50  ...   3.45     1480                 1
4      13.24        2.59  2.87  ...   2.93      735                 1
..       ...         ...   ...  ...    ...      ...               ...
173    13.71        5.65  2.45  ...   1.74      740                 3
174    13.40        3.91  2.48  ...   1.56      750                 3
175    13.27        4.28  2.26  ...   1.56      835                 3
176    13.17        2.59  2.37  ...   1.62      840                 3
177    14.13        4.10  2.74  ...   1.60      560                 3

[178 rows x 14 columns]

## Bước 2: Chia 2 trường dữ liệu ra X, y

(     Alcohol  Malic_Acid   Ash  ...   Hue  OD280  Proline
 0      14.23        1.71  2.43  ...  1.04   3.92     1065
 1      13.20        1.78  2.14  ...  1.05   3.40     1050
 2      13.16        2.36  2.67  ...  1.03   3.17     1185
 3      14.37        1.95  2.50  ...  0.86   3.45     1480
 4      13.24        2.59  2.87  ...  1.04   2.93      735
 ..       ...         ...   ...  ...   ...    ...      ...
 173    13.71        5.65  2.45  ...  0.64   1.74      740
 174    13.40        3.91  2.48  ...  0.70   1.56      750
 175    13.27        4.28  2.26  ...  0.59   1.56      835
 176    13.17        2.59  2.37  ...  0.60   1.62      840
 177    14.13        4.10  2.74  ...  0.61   1.60      560
 
 [178 rows x 13 columns], 0      1
 1      1
 2      1
 3      1
 4      1
       ..
 173    3
 174    3
 175    3
 176    3
 177    3
 Name: Customer_Segment, Length: 178, dtype: int64)

## Bước 3: Chuẩn hóa dữ liệu bằng StandardScaler

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

## Bước 4: PCA để nén đặc trưng dữ liệu đầu vào (dim = 13 -> dim = 2)

array([[ 3.31675081, -1.44346263],
       [ 2.20946492,  0.33339289],
       [ 2.51674015, -1.0311513 ],
       [ 3.75706561, -2.75637191],
       [ 1.00890849, -0.86983082],
       [ 3.05025392, -2.12240111],
       [ 2.44908967, -1.17485013],
       [ 2.05943687, -1.60896307],
       [ 2.5108743 , -0.91807096],
       [ 2.75362819, -0.78943767],
       [ 3.47973668, -1.30233324],
       [ 1.7547529 , -0.61197723],
       [ 2.11346234, -0.67570634],
       [ 3.45815682, -1.13062988],
       [ 4.31278391, -2.09597558],
       [ 2.3051882 , -1.66255173],
       [ 2.17195527, -2.32730534],
       [ 1.89897118, -1.63136888],
       [ 3.54198508, -2.51834367],
       [ 2.0845222 , -1.06113799],
       [ 3.12440254, -0.78689711],
       [ 1.08657007, -0.24174355],
       [ 2.53522408,  0.09184062],
       [ 1.64498834,  0.51627893],
       [ 1.76157587,  0.31714893],
       [ 0.9900791 , -0.94066734],
       [ 1.77527763, -0.68617513],
       [ 1.23542396,  0.08980704],
       [ 2.18840633,

## Bước 6: Dùng Logistic Regression để phân lớp dữ liệu

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

array([1, 1, 3, 1, 2, 1, 2, 3, 2, 3, 1, 3, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2,
       2, 3, 3, 3, 2, 2, 2, 1, 1, 2, 3, 1, 1, 1])

## Bước 7: Đánh giá mô hình với độ đo accuracy

1.0


## Bước 8: Đánh giá mô hình bằng K-fold cross validation với k = 5

array([1.        , 0.94444444, 0.94444444, 0.97142857, 0.97142857])

In [56]:
print(f"Accuracy: {np.mean(scores)}")

Accuracy: 0.9663492063492063
